"""Constants."""

MAX_CONCURRENCY = 30
MAX_FILE_BATCH_SIZE = 5
MAX_RETRY_ATTEMPTS = 3
REQUEST_TIMEOUT = 30

DEFAULT_URL = "https://api.redbrickai.com"

PEERLESS_ERRORS = (
    KeyboardInterrupt,
    PermissionError,
    TimeoutError,
    ConnectionError,
    ValueError,
    SystemError,
    SystemExit,
)

DUMMY_FILE_PATH = "https://test"


ALTADB_STORAGE_PROVIDER = "ALTA_DB"
AWS_S3_STORAGE_PROVIDER = "AWS_S3"
AZURE_BLOB_STORAGE_PROVIDER = "AZURE_BLOB"
GCS_STORAGE_PROVIDER = "GCS"
REDBRICK_STORAGE_PROVIDER = "REDBRICK"
PUBLIC_STORAGE_PROVIDER = "PUBLIC"

STORAGE_PROVIDER_KEY_MAP = {
    ALTADB_STORAGE_PROVIDER: "altaDb",
    AWS_S3_STORAGE_PROVIDER: "s3Bucket",
    AZURE_BLOB_STORAGE_PROVIDER: "azureBucket",
    GCS_STORAGE_PROVIDER: "gcsBucket",
    REDBRICK_STORAGE_PROVIDER: "redbrick",
    PUBLIC_STORAGE_PROVIDER: "public",
}
