"""Enumerations for use across SDK."""

from enum import Enum


class LabelType(Enum):
    """Allowable types for labeling projects."""

    IMAGE_ITEMS = "IMAGE_ITEMS"
    IMAGE_CLASSIFY = "IMAGE_CLASSIFY"
    IMAGE_BBOX = "IMAGE_BBOX"
    IMAGE_POINT = "IMAGE_POINT"
    IMAGE_POLYLINE = "IMAGE_POLYLINE"
    IMAGE_POLYGON = "IMAGE_POLYGON"
    IMAGE_ELLIPSE = "IMAGE_ELLIPSE"
    IMAGE_SEGMENTATION = "IMAGE_SEGMENTATION"
    IMAGE_MULTI = "IMAGE_MULTI"

    VIDEO_ITEMS = "VIDEO_ITEMS"
    VIDEO_BBOX = "VIDEO_BBOX"
    VIDEO_POINT = "VIDEO_POINT"
    VIDEO_POLYLINE = "VIDEO_POLYLINE"
    VIDEO_ELLIPSE = "VIDEO_ELLIPSE"
    VIDEO_CLASSIFY = "VIDEO_CLASSIFY"
    VIDEO_POLYGON = "VIDEO_POLYGON"
    VIDEO_MULTI = "VIDEO_MULTI"

    DOCUMENT_BBOX = "DOCUMENT_BBOX"

    DICOM_SEGMENTATION = "DICOM_SEGMENTATION"


class StorageMethod:
    """Special case storage method Ids."""

    PUBLIC = "11111111-1111-1111-1111-111111111111"
    REDBRICK = "22222222-2222-2222-2222-222222222222"


class TaskStates(Enum):
    """Potential states of task status."""

    UNASSIGNED = "UNASSIGNED"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    PROBLEM = "PROBLEM"
